# This file contains all available configuration options
# with their default values.

# all available settings of specific linters
linters-settings:
  golint:
    min-confidence: 0.4
  gocyclo:
    min-complexity: 12

linters:
  enable:
    - golint
    - gocyclo

issues:
  # Independently from option `exclude` we use default exclude patterns,
  # it can be disabled by this option. To list all
  # excluded by default patterns execute `golangci-lint run --help`.
  exclude-use-default: false